"""Add generic metric store foundation

Revision ID: 0018
Revises: e17a9cb848b6
Create Date: 2026-03-19 10:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0018_add_metric_store_foundation"
down_revision = "e17a9cb848b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "definitions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("metric_code", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("metric_code"),
        schema="metrics",
    )
    op.create_table(
        "dim_dates",
        sa.Column("time_id", sa.INTEGER(), nullable=False),
        sa.Column("full_date", sa.DATE(), nullable=False),
        sa.Column("week_num", sa.INTEGER(), nullable=False),
        sa.Column("month_num", sa.INTEGER(), nullable=False),
        sa.Column("quarter", sa.INTEGER(), nullable=False),
        sa.Column("year", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("time_id"),
        sa.UniqueConstraint("full_date"),
        schema="metrics",
    )
    op.create_table(
        "grains",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("grain_code", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grain_code"),
        schema="metrics",
    )
    op.create_table(
        "calculations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("definition_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("calc_code", sa.TEXT(), nullable=False),
        sa.Column("grain_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("unit_code", sa.TEXT(), nullable=False),
        sa.Column(
            "uses_commitment_points",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"], ["metrics.definitions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["grain_id"],
            ["metrics.grains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calc_code"),
        schema="metrics",
    )
    op.create_table(
        "dim_projects",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_key", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["clean_jira.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
        schema="metrics",
    )
    op.create_table(
        "slice_rules",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("rule_name", sa.TEXT(), nullable=False),
        sa.Column("target_definition_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("target_definition_name", sa.TEXT(), nullable=True),
        sa.Column("source_table", sa.TEXT(), nullable=False),
        sa.Column("group_by_source_column", sa.TEXT(), nullable=False),
        sa.Column(
            "enabled", sa.BOOLEAN(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["clean_jira.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_definition_id"], ["metrics.definitions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="metrics",
    )
    op.create_table(
        "units",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("unit_code", sa.TEXT(), nullable=False),
        sa.Column("display_symbol", sa.TEXT(), nullable=False),
        sa.Column("source_field_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_entity", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["clean_jira.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_field_id"], ["clean_jira.field_keys.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="metrics",
    )
    op.create_index(
        "idx_unique_unit_code_global",
        "units",
        ["unit_code"],
        unique=True,
        schema="metrics",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.create_index(
        "idx_unique_unit_code_project",
        "units",
        ["project_id", "unit_code"],
        unique=True,
        schema="metrics",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )

    op.create_table(
        "commitment_rules",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("board_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "target_calculation_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("target_calculation_name", sa.TEXT(), nullable=False),
        sa.Column("start_column_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("end_column_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("start_column_name_snapshot", sa.TEXT(), nullable=False),
        sa.Column("end_column_name_snapshot", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["board_id"], ["clean_jira.boards.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["end_column_id"], ["clean_jira.board_columns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["clean_jira.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["start_column_id"], ["clean_jira.board_columns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_calculation_id"], ["metrics.calculations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="metrics",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commitment_rules", schema="metrics")
    op.drop_index("idx_unique_unit_code_project", table_name="units", schema="metrics")
    op.drop_index("idx_unique_unit_code_global", table_name="units", schema="metrics")
    op.drop_table("units", schema="metrics")
    op.drop_table("slice_rules", schema="metrics")
    op.drop_table("dim_projects", schema="metrics")
    op.drop_table("calculations", schema="metrics")
    op.drop_table("grains", schema="metrics")
    op.drop_table("dim_dates", schema="metrics")
    op.drop_table("definitions", schema="metrics")
    # ### end Alembic commands ###
