"""
Utilities for working with Polars DataFrames and PostgreSQL database.

This module provides helper functions to:
- Read SQL query results into Polars DataFrames
- Write Polars DataFrames back to PostgreSQL tables
"""


import polars as pl
from sqlalchemy import Engine, text


def read_table(engine: Engine, query: str) -> pl.DataFrame:
    """
    Read SQL query results into a Polars DataFrame.

    This function executes a SQL query and returns the result as a Polars DataFrame.
    Under the hood, it uses Pandas as a bridge for compatibility with SQLAlchemy.

    Args:
        engine: SQLAlchemy Engine instance
        query: SQL query string to execute

    Returns:
        Polars DataFrame containing query results

    Example:
        >>> engine = create_engine("postgresql://...")
        >>> df = read_table(engine, "SELECT * FROM clean_jira.issues")
        >>> print(df.shape)
    """
    from uuid import UUID

    import pandas as pd

    # Use Pandas as bridge (SQLAlchemy has native support)
    pdf = pd.read_sql(query, engine)

    # Convert UUID columns to strings (PyArrow doesn't recognize UUID type)
    for col in pdf.columns:
        if len(pdf) > 0 and isinstance(pdf[col].iloc[0], UUID):
            pdf[col] = pdf[col].astype(str)

    # Convert to Polars
    return pl.from_pandas(pdf)


def write_table(
    df: pl.DataFrame,
    engine: Engine,
    table: str,
    schema: str = "metrics",
    if_exists: str = "replace",
) -> None:
    """
    Write Polars DataFrame to a PostgreSQL table.

    This function writes data to PostgreSQL using TRUNCATE + INSERT pattern
    (when if_exists='replace'). It converts Polars to Pandas first for compatibility.

    Args:
        df: Polars DataFrame to write
        engine: SQLAlchemy Engine instance
        table: Table name (without schema)
        schema: Schema name (default: "metrics")
        if_exists: What to do if table exists: 'replace', 'append', 'fail'

    Example:
        >>> velocity_df = pl.DataFrame({"sprint_id": [1, 2], "velocity": [10, 12]})
        >>> write_table(velocity_df, engine, "fact_velocity", schema="metrics")
    """
    # Convert to Pandas for SQLAlchemy compatibility
    pdf = df.to_pandas()

    # Drop columns that should be auto-generated by PostgreSQL
    # (id, created_at, updated_at have DEFAULT values in schema)
    columns_to_drop = []
    for col in ["id", "created_at", "updated_at"]:
        if col in pdf.columns and pdf[col].isna().all():
            columns_to_drop.append(col)

    if columns_to_drop:
        pdf = pdf.drop(columns=columns_to_drop)

    # If replacing, use TRUNCATE instead of DROP to preserve dependent views
    if if_exists == "replace":
        with engine.connect() as conn:
            # TRUNCATE is faster than DELETE and resets sequences
            # CASCADE ensures dependent objects aren't affected
            conn.execute(text(f"TRUNCATE TABLE {schema}.{table} RESTART IDENTITY"))
            conn.commit()

        # Now append to the empty table
        pdf.to_sql(
            name=table,
            con=engine,
            schema=schema,
            if_exists="append",  # Table exists, just append
            index=False,
            method="multi",
        )
    else:
        # For 'append' or 'fail', use pandas default behavior
        pdf.to_sql(
            name=table,
            con=engine,
            schema=schema,
            if_exists=if_exists,
            index=False,
            method="multi",
        )


def execute_sql(engine: Engine, sql: str) -> None:
    """
    Execute raw SQL statement (for DDL operations like CREATE TABLE).

    Args:
        engine: SQLAlchemy Engine instance
        sql: SQL statement to execute

    Example:
        >>> execute_sql(engine, "DROP MATERIALIZED VIEW IF EXISTS metrics.fact_velocity CASCADE")
    """
    with engine.connect() as conn:
        conn.execute(text(sql))
        conn.commit()
