"""
Utilities for working with Polars DataFrames and PostgreSQL database.

This module provides helper functions to:
- Read SQL query results into Polars DataFrames
- Write Polars DataFrames back to PostgreSQL tables
"""

import json
import logging
import os

import polars as pl
from sqlalchemy import Engine, text

logger = logging.getLogger(__name__)


def read_table(
    engine: Engine, query: str, params: dict | list | tuple = None
) -> pl.DataFrame:
    """
    Read SQL query results into a Polars DataFrame.

    This function executes a SQL query and returns the result as a Polars DataFrame.
    It uses Polars' native read_database_uri for better performance.

    Args:
        engine: SQLAlchemy Engine instance
        query: SQL query string to execute
        params: Optional parameters to pass to the query

    Returns:
        Polars DataFrame containing query results
    """
    from datetime import date, datetime

    import pandas as pd

    if not params:
        # Fast path used by tests and by read-only queries.
        try:
            return pl.read_database_uri(query=query, uri=str(engine.url))
        except Exception:
            # Fallback for complex types/driver edge-cases.
            with engine.connect() as conn:
                pdf = pd.read_sql(text(query), conn)
                for col in pdf.columns:
                    if pdf[col].dtype == "object":
                        # Skip string conversion for datetime objects to avoid destruction
                        sample = pdf[col].dropna().head(1)
                        if not sample.empty and isinstance(
                            sample.iloc[0], (datetime, date)
                        ):
                            continue
                        pdf[col] = pdf[col].astype(str)
                return pl.from_pandas(pdf)

    # Parameterized path: use pandas/SQLAlchemy safely.
    with engine.connect() as conn:
        pdf = pd.read_sql(text(query), conn, params=params)
        for col in pdf.columns:
            if pdf[col].dtype == "object":
                # Skip string conversion for datetime objects to avoid destruction
                sample = pdf[col].dropna().head(1)
                if not sample.empty and isinstance(sample.iloc[0], (datetime, date)):
                    continue
                pdf[col] = pdf[col].astype(str)
        return pl.from_pandas(pdf)


def write_fact_values(
    df: pl.DataFrame,
    engine: Engine,
    metric_ids: list[str],
    project_agg_ids: list[str],
    time_id_start: int,
    time_id_end: int,
) -> int:
    """
    Atomic idempotent write of fact_values rows.

    Algorithm:
    1. Create temp staging table: _fact_values_stage
    2. Load new rows into _fact_values_stage
    3. In a SINGLE transaction:
       a. DELETE existing rows WHERE metric_id/project_agg_id/time_id match
       b. INSERT FROM _fact_values_stage
    4. DROP temp table

    Returns: number of rows inserted
    """
    if df.is_empty() and not metric_ids:
        return 0

    # 0. Validate Schema
    required_cols = {"metric_id", "project_agg_id", "time_id", "value"}
    missing = required_cols - set(df.columns)
    if not df.is_empty() and missing:
        raise ValueError(
            f"DataFrame is missing required fact_values columns: {missing}"
        )

    # 1. Prepare data for insertion (UUIDs as strings for SQLAlchemy/Pandas)
    pdf = None
    if not df.is_empty():
        # Serialize Struct columns to JSON strings - psycopg2 cannot adapt dict values
        struct_cols = [c for c in df.columns if str(df[c].dtype).startswith("Struct")]
        if struct_cols:
            df = df.with_columns(
                [
                    pl.col(c).map_elements(
                        lambda x: json.dumps(x) if x is not None else None,
                        return_dtype=pl.Utf8,
                    )
                    for c in struct_cols
                ]
            )
        pdf = df.to_pandas()
        # Drop columns that should be auto-generated by PostgreSQL
        columns_to_drop = []
        for col in ["id", "created_at", "updated_at"]:
            if col in pdf.columns and pdf[col].isna().all():
                columns_to_drop.append(col)
        if columns_to_drop:
            pdf = pdf.drop(columns=columns_to_drop)

        # Stringify UUIDs
        for col in [
            "metric_id",
            "project_agg_id",
            "slice_rule_id",
            "commitment_rule_id",
            "settings_id",
        ]:
            if col in pdf.columns:
                pdf[col] = pdf[col].apply(lambda x: str(x) if x is not None else None)

    # 2. Execute atomic transaction
    with engine.begin() as conn:
        # a. Create temp staging table (LIKE final table but without constraints/indexes for speed)
        conn.execute(
            text(
                "CREATE TEMP TABLE _fact_values_stage (LIKE metrics.fact_values INCLUDING DEFAULTS)"
            )
        )

        # b. Load data into staging table
        if pdf is not None and not pdf.empty:
            pdf.to_sql(
                name="_fact_values_stage",
                con=conn,
                if_exists="append",
                index=False,
                method="multi",
                chunksize=5000,
            )

        # c. Optional advisory lock for concurrent writers
        use_advisory_lock = (
            os.getenv("FACT_VALUES_USE_ADVISORY_LOCK", "true").lower() != "false"
        )
        if use_advisory_lock and metric_ids:
            # Hash all metric IDs together for a stable per-metric-set lock
            lock_key = "_".join(sorted(metric_ids))
            conn.execute(
                text("SELECT pg_advisory_xact_lock(hashtext(:lock_key))"),
                {"lock_key": lock_key},
            )

        # d. DELETE existing rows
        delete_query = text(
            """
            DELETE FROM metrics.fact_values
            WHERE metric_id = ANY(CAST(:metric_ids AS uuid[]))
              AND project_agg_id = ANY(CAST(:project_agg_ids AS uuid[]))
              AND time_id BETWEEN :start AND :end
            """
        )
        conn.execute(
            delete_query,
            {
                "metric_ids": metric_ids,
                "project_agg_ids": project_agg_ids,
                "start": time_id_start,
                "end": time_id_end,
            },
        )

        # e. INSERT from staging to final
        if pdf is not None and not pdf.empty:
            # Match columns explicitly in case of schema drifts
            cols = ", ".join([f'"{c}"' for c in pdf.columns])
            insert_sql = f"INSERT INTO metrics.fact_values ({cols}) SELECT {cols} FROM _fact_values_stage"  # noqa: S608
            # Column identifiers come from in-process DataFrame schema and are quoted.
            conn.execute(text(insert_sql))

        # Temp table auto-dropped at transaction end if CREATE TEMP ... ON COMMIT DROP was used,
        # but here we use session-scope temp table which is also fine.
        conn.execute(text("DROP TABLE _fact_values_stage"))

    return len(df)


def execute_sql(engine: Engine, sql: str) -> None:
    """
    Execute raw SQL statement.

    Args:
        engine: SQLAlchemy Engine instance
        sql: SQL statement to execute
    """
    with engine.connect() as conn:
        conn.execute(text(sql))
        conn.commit()
