"""
Utilities for working with Polars DataFrames and PostgreSQL database.

This module provides helper functions to:
- Read SQL query results into Polars DataFrames
- Write Polars DataFrames back to PostgreSQL tables
"""

import os

import polars as pl
from sqlalchemy import Engine, text


def read_table(
    engine: Engine, query: str, params: dict | list | tuple = None
) -> pl.DataFrame:
    """
    Read SQL query results into a Polars DataFrame.

    This function executes a SQL query and returns the result as a Polars DataFrame.
    It uses Polars' native read_database_uri for better performance.

    Args:
        engine: SQLAlchemy Engine instance
        query: SQL query string to execute
        params: Optional parameters to pass to the query

    Returns:
        Polars DataFrame containing query results
    """
    from datetime import date, datetime

    import pandas as pd

    if not params:
        # Fast path used by tests and by read-only queries.
        try:
            return pl.read_database_uri(query=query, uri=str(engine.url))
        except Exception:
            # Fallback for complex types/driver edge-cases.
            with engine.connect() as conn:
                pdf = pd.read_sql(text(query), conn)
                for col in pdf.columns:
                    if pdf[col].dtype == "object":
                        # Skip string conversion for datetime objects to avoid destruction
                        sample = pdf[col].dropna().head(1)
                        if not sample.empty and isinstance(
                            sample.iloc[0], (datetime, date)
                        ):
                            continue
                        pdf[col] = pdf[col].astype(str)
                return pl.from_pandas(pdf)

    # Parameterized path: use pandas/SQLAlchemy safely.
    with engine.connect() as conn:
        pdf = pd.read_sql(text(query), conn, params=params)
        for col in pdf.columns:
            if pdf[col].dtype == "object":
                # Skip string conversion for datetime objects to avoid destruction
                sample = pdf[col].dropna().head(1)
                if not sample.empty and isinstance(sample.iloc[0], (datetime, date)):
                    continue
                pdf[col] = pdf[col].astype(str)
        return pl.from_pandas(pdf)


def write_table(
    df: pl.DataFrame,
    engine: Engine,
    table: str,
    schema: str = "metrics",
    if_exists: str = "replace",
) -> None:
    """
    Write Polars DataFrame to a PostgreSQL table.

    This function writes data to PostgreSQL using TRUNCATE + INSERT pattern
    (when if_exists='replace'). It converts Polars to Pandas first for compatibility.

    Args:
        df: Polars DataFrame to write
        engine: SQLAlchemy Engine instance
        table: Table name (without schema)
        schema: Schema name (default: "metrics")
        if_exists: What to do if table exists: 'replace', 'append', 'fail'
    """
    # Convert to Pandas for SQLAlchemy compatibility
    pdf = df.to_pandas()

    # Drop columns that should be auto-generated by PostgreSQL
    columns_to_drop = []
    for col in ["id", "created_at", "updated_at"]:
        if col in pdf.columns and pdf[col].isna().all():
            columns_to_drop.append(col)

    if columns_to_drop:
        pdf = pdf.drop(columns=columns_to_drop)

    if if_exists == "replace":
        with engine.connect() as conn:
            # TRUNCATE is faster than DELETE and resets sequences
            conn.execute(
                text(f"TRUNCATE TABLE {schema}.{table} RESTART IDENTITY CASCADE")
            )
            conn.commit()

        # Now append to the empty table
        pdf.to_sql(
            name=table,
            con=engine,
            schema=schema,
            if_exists="append",
            index=False,
            method="multi",
        )
    else:
        pdf.to_sql(
            name=table,
            con=engine,
            schema=schema,
            if_exists=if_exists,
            index=False,
            method="multi",
        )


def write_fact_values(
    df: pl.DataFrame,
    engine: Engine,
    metric_ids: list[str],
    project_agg_ids: list[str],
    time_id_start: int,
    time_id_end: int,
) -> int:
    """
    Idempotent write of fact_values rows.

    Algorithm:
    1. DELETE rows WHERE metric_id IN (:metric_ids)
                      AND project_agg_id IN (:project_agg_ids)
                      AND time_id BETWEEN :start AND :end
    2. INSERT new rows via ADBC (COPY protocol)

    Returns: number of rows inserted
    """
    uri = str(engine.url)

    # 1. DELETE existing rows (with advisory lock for concurrency safety)
    delete_query = text(
        """
        DELETE FROM metrics.fact_values
        WHERE metric_id = ANY(CAST(:metric_ids AS uuid[]))
          AND project_agg_id = ANY(CAST(:project_agg_ids AS uuid[]))
          AND time_id BETWEEN :start AND :end
    """
    )

    with engine.begin() as conn:
        # Optional advisory lock for concurrent writers.
        use_advisory_lock = (
            os.getenv("FACT_VALUES_USE_ADVISORY_LOCK", "false").lower() == "true"
        )
        if use_advisory_lock and metric_ids:
            # We use hashtext to get a 32-bit integer for the lock
            conn.execute(
                text("SELECT pg_advisory_xact_lock(hashtext(:lock_key))"),
                {"lock_key": str(metric_ids[0])},
            )

        conn.execute(
            delete_query,
            {
                "metric_ids": metric_ids,
                "project_agg_ids": project_agg_ids,
                "start": time_id_start,
                "end": time_id_end,
            },
        )

    if df.is_empty():
        return 0

    # 2. INSERT via ADBC
    try:
        # Polars write_database with engine="adbc" uses COPY protocol
        df.write_database(
            table_name="metrics.fact_values",
            connection=uri,
            if_table_exists="append",
            engine="adbc",
        )
    except Exception as e:
        # Graceful fallback to Pandas if ADBC fails
        import logging

        logging.warning(f"ADBC write failed, falling back to Pandas: {e}")
        pdf = df.to_pandas()
        pdf.to_sql(
            name="fact_values",
            con=engine,
            schema="metrics",
            if_exists="append",
            index=False,
            method="multi",
            chunksize=5000,
        )

    return len(df)


def execute_sql(engine: Engine, sql: str) -> None:
    """
    Execute raw SQL statement.

    Args:
        engine: SQLAlchemy Engine instance
        sql: SQL statement to execute
    """
    with engine.connect() as conn:
        conn.execute(text(sql))
        conn.commit()
